//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToolFahrrad_v1.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToolFahrrad_v1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Down_Arrow_Icon1 {
            get {
                object obj = ResourceManager.GetObject("Down-Arrow-Icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestand ähnelt.
        /// </summary>
        internal static string Fahrrad_Information_B {
            get {
                return ResourceManager.GetString("Fahrrad_Information_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Periode ähnelt.
        /// </summary>
        internal static string Fahrrad_Information_P {
            get {
                return ResourceManager.GetString("Fahrrad_Information_P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trend ähnelt.
        /// </summary>
        internal static string Fahrrad_Information_Trend {
            get {
                return ResourceManager.GetString("Fahrrad_Information_Trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  kann nicht keine Menge haben. 
        ///Diese zeile wird ignoriert ähnelt.
        /// </summary>
        internal static string Fahrrad_pictureBox3_Click_ {
            get {
                return ResourceManager.GetString("Fahrrad_pictureBox3_Click_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  exsistiert nicht im System. 
        ///Diese zeile wird ignoriert ähnelt.
        /// </summary>
        internal static string Fahrrad_pictureBox3_Click_1 {
            get {
                return ResourceManager.GetString("Fahrrad_pictureBox3_Click_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kaufteil kann nicht NULL sein ähnelt.
        /// </summary>
        internal static string Fahrrad_pictureBox3_Click_Kaufteil_kann_nicht_NULL_sein {
            get {
                return ResourceManager.GetString("Fahrrad_pictureBox3_Click_Kaufteil_kann_nicht_NULL_sein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kaufteil N ähnelt.
        /// </summary>
        internal static string Fahrrad_pictureBox3_Click_Kaufteil_N {
            get {
                return ResourceManager.GetString("Fahrrad_pictureBox3_Click_Kaufteil_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenfertigte Teil N ähnelt.
        /// </summary>
        internal static string Fahrrad_saveAenderungen2_Click_Eigenfertigte_Teil_N {
            get {
                return ResourceManager.GetString("Fahrrad_saveAenderungen2_Click_Eigenfertigte_Teil_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eigenfertigte Teil N ähnelt.
        /// </summary>
        internal static string Fahrrad_saveAenderungen2_Click_Eigenfertigte_Teil_N1 {
            get {
                return ResourceManager.GetString("Fahrrad_saveAenderungen2_Click_Eigenfertigte_Teil_N1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die kein Fehld darf null sein ähnelt.
        /// </summary>
        internal static string Fahrrad_saveAenderungen2_Click_kein_Fehld_darf_null_sein {
            get {
                return ResourceManager.GetString("Fahrrad_saveAenderungen2_Click_kein_Fehld_darf_null_sein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Periode  ähnelt.
        /// </summary>
        internal static string Fahrrad_toolAusfueren_Click_Periode_ {
            get {
                return ResourceManager.GetString("Fahrrad_toolAusfueren_Click_Periode_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forcast  ähnelt.
        /// </summary>
        internal static string Fahrrad_toolAusfueren_Click_Periode_en {
            get {
                return ResourceManager.GetString("Fahrrad_toolAusfueren_Click_Periode_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xml-Datei erstellen ähnelt.
        /// </summary>
        internal static string Fahrrad_XmlExport_xml_Datei_erstellen {
            get {
                return ResourceManager.GetString("Fahrrad_XmlExport_xml_Datei_erstellen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehlermeldung ähnelt.
        /// </summary>
        internal static string Fahrrad_XmlOeffnen_Fehlermeldung {
            get {
                return ResourceManager.GetString("Fahrrad_XmlOeffnen_Fehlermeldung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde zum Laden falsche Datei ausgewählt. 
        ///Das Programm kann nicht ausgeführt werden ähnelt.
        /// </summary>
        internal static string Fahrrad_XmlOeffnen_TEXT {
            get {
                return ResourceManager.GetString("Fahrrad_XmlOeffnen_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die xml-Datei öffnen (*.xml)|*.xml ähnelt.
        /// </summary>
        internal static string Fahrrad_XmlOeffnen_xml_Datei_öffnen____xml____xml {
            get {
                return ResourceManager.GetString("Fahrrad_XmlOeffnen_xml_Datei_öffnen____xml____xml", resourceCulture);
            }
        }
    }
}
